### PR TITLE
Update 02-deploy-random-ipfs-nft.js

### PR DESCRIPTION
**Pull request by RoboCrypter**
Merge it and try it out now!

### CODE REVIEW

**Review by SpeedBird789 — COMMENTED** [review]
strangely, still the same error

**Comment by RoboCrypter** [comment]
> strangely, still the same error

Still looking!

**Comment by RoboCrypter** [comment]
@SpeedBird789 : Beside this PR code is perfect, I have tested it. Check your discussion!

**Comment by RoboCrypter** [comment]
@SpeedBird789 : I'm closing this PR as you don't need this anymore!

**Pull request closed without merging**
